Repository coders-school/password-manager, pull requests merged in 2024-03, with the labels that each got.

#45 Boost library integration
  .github/workflows/cmake_ci.yml
  source/CMakeLists.txt
Labels: Standard

#37 Encryption
  encrypt/.gitignore
  encrypt/CMakeLists.txt
  encrypt/README.md
  encrypt/hash/FakeHash.cpp
  encrypt/hash/FakeHash.hpp
  encrypt/hash/IHash.hpp
  encrypt/hash/SHA512.cpp
  encrypt/hash/SHA512.hpp
  encrypt/symCrypt/AES256CBC.cpp
  encrypt/symCrypt/AES256CBC.hpp
  encrypt/symCrypt/FakeSymCipher.cpp
  encrypt/symCrypt/FakeSymCipher.hpp
  encrypt/symCrypt/ISymCipher.hpp
  encrypt/uTests/CMakeLists.txt
  encrypt/uTests/symCrypt/AES256CBCTests.cpp
  encrypt/uTests/symCrypt/SHA512Tests.cpp
Labels: Standard, Unknown user

#38 Configure qt project
  .github/workflows/cmake_ci.yml
  CMakeLists.txt
  source/Backend/CMakeLists.txt
  source/Backend/Common/Logger.cpp
  source/Backend/Common/Logger.hpp
  source/Backend/DataBase/CMakeLists.txt
  source/Backend/DataBase/DataBaseHandler.cpp
  source/Backend/DataBase/DataBaseHandler.hpp
  source/Backend/DataBase/common/DataBaseCommon.hpp
  source/Backend/DataBase/password-manager.db
  source/Backend/PasswordManager.cpp
  source/Backend/main.cpp
  source/CMakeLists.txt
  source/Frontend/CMakeLists.txt
  source/Frontend/src/app/CMakeLists.txt
  source/Frontend/src/app/main.cpp
  source/Frontend/src/app/mainwindow.cpp
  source/Frontend/src/app/mainwindow.h
  source/Frontend/src/app/mainwindow.ui
  source/Test/CMakeLists.txt
  source/Test/test.cpp
Labels: Standard, Auto-closed

#46 New DataBaseManagment
  source/Backend/DataBase/CMakeLists.txt
  source/Backend/DataBase/DataBaseConnection.cpp
  source/Backend/DataBase/DataBaseConnection.hpp
  source/Backend/DataBase/DataBaseHandler.cpp
  source/Backend/DataBase/DataBaseHandler.hpp
  source/Backend/DataBase/DataBaseManager.cpp
  source/Backend/DataBase/DataBaseManager.hpp
  source/Backend/DataBase/QueryOperationBuilder.cpp
  source/Backend/DataBase/QueryOperationBuilder.hpp
  source/Backend/DataBase/common/DataBaseCommon.hpp
  source/Backend/DataBase/common/DataBaseRequest.hpp
  source/Backend/DataBase/interface/IDataBaseConnection.hpp
  source/Backend/DataBase/interface/IDataBaseManager.hpp
  source/Backend/DataBase/interface/IQueryOperationBuilder.hpp
  source/Backend/DataBase/password-manager.db
  source/Backend/main.cpp
  source/Test/CMakeLists.txt
  source/Test/DataBaseManagerTests.cpp
  source/Test/QueryOperationBuilderTests.cpp
  source/Test/mocks/DataBaseConnectionMock.hpp
  source/Test/mocks/DataBaseManagerMock.hpp
  source/Test/mocks/QueryOperationBuilderMock.hpp
Labels: Standard
